apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    editable: true

  - name: Loki
    type: loki
    url: http://loki:9100
    access: proxy
    editable: true